### ISSUE TITLE
Update to C-lightning 0.10

### ISSUE THREAD

**Issue by darosior** [lightningamp/lamp#98]
Looks like it's already part of `lightning_ndk`, which just has to be released

**Comment by vincenzopalazzo** [comment]
Yep correct, maybe @lvaccaro can fix it :)

**Comment by darosior** [comment]
Any update on this? It's been more than a month and i wanted to brag about Lamp in Miami :p (and i can't use the current version, but the conference starts in 2days..)

**Comment by vincenzopalazzo** [comment]
Hi @darosior  if @lvaccaro is busy; tomorrow night I can make a fake PR to redirect the link of lamp in my fork, so you will be able to bring lamp to Miami :-D for sure

**Comment by darosior** [comment]
Thanks! Would be awesome

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vincenzopalazzo** [comment]
ping @darosior Lamp with lightningd 0.10.0 ready on my branch https://github.com/vincenzopalazzo/lamp/tree/miami

Ping me if you have any problems.

**Comment by lvaccaro** [comment]
I think you have permissions to merge stuff on master

**Comment by darosior** [comment]
@lvaccaro i think what was preventing it wasn't merging the code to fetch the v0.10 from `lightning_ndk`, but an actual `lightning_ndk` release to be able to fetch it in the first place.

@vincenzopalazzo looks like your branch is working for me, thanks! Now trying to sync :) `v0.10_miami` made me smile ("Lamp Florida Edition" lol).

NB: the organisation name contains a typo, `s//ightningamp/lightninglamp/`

**Comment by vincenzopalazzo** [comment]
>@vincenzopalazzo looks like your branch is working for me, thanks! Now trying to sync :) v0.10_miami made me smile ("Lamp Florida Edition" lol).

ack for the name in this case 😄 

>NB: the organisation name contains a typo, s//ightningamp/lightninglamp/

Unfortunately, the name is not a typo but a hotfix with the collision of the organization name 😿

**Comment by lvaccaro** [comment]
Miami edition looks really cool :-) thanks @vincenzopalazzo to take care about the release.

@darosior have you any ideas about a cool org name?
